import { app, BrowserWindow, dialog, ipcMain, Menu } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { runOrderPipeline } from './services/pipeline';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

function sendLog(message: string): void {
  mainWindow?.webContents.send('pipeline-log', message);
}

// ready 이전에 등록해도 되며, whenReady 안에만 두면 HMR/로드 순서로 핸들러가 없을 수 있음
ipcMain.handle('select-excel-file', async () => {
  const parent = BrowserWindow.getFocusedWindow() ?? mainWindow ?? undefined;
  const r = await dialog.showOpenDialog(parent, {
    properties: ['openFile'],
    filters: [{ name: 'Excel', extensions: ['xlsx', 'xls', 'xlsm'] }],
  });
  if (r.canceled || r.filePaths.length === 0) {
    return null;
  }
  return r.filePaths[0];
});

ipcMain.handle(
  'run-pipeline',
  async (
    _event,
    filePath: unknown,
    marketKey: unknown,
  ): Promise<{ ok: boolean; error?: string }> => {
    if (typeof filePath !== 'string' || !filePath.trim()) {
      return { ok: false, error: '파일 경로가 없습니다.' };
    }
    if (
      marketKey !== 'gmarket' &&
      marketKey !== 'naver' &&
      marketKey !== 'auction' &&
      marketKey !== '11st' &&
      marketKey !== 'ohou'
    ) {
      return { ok: false, error: '사이트 선택 값이 올바르지 않습니다.' };
    }
    const resolved = path.resolve(filePath.trim());
    if (!fs.existsSync(resolved)) {
      return { ok: false, error: '파일을 찾을 수 없습니다.' };
    }
    try {
      await runOrderPipeline(resolved, (m) => sendLog(m), { marketKey });
      return { ok: true };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      sendLog(`오류: ${msg}`);
      return { ok: false, error: msg };
    }
  },
);

const createWindow = (): void => {
  mainWindow = new BrowserWindow({
    height: 630,
    width: 760,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
    },
  });

  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools({ mode: 'detach' });
  }
};

app.whenReady().then(() => {
  Menu.setApplicationMenu(null);
  createWindow();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
